### ISSUE TITLE
__getattr__ of DotNotationDict should raise AttributeError

### ISSUE THREAD

**Issue by svisser** [joealcorn/xbox#2]
For correctness, the `__getattr__` method of `DotNotationDict` needs to raise an `AttributeError` when the attribute does not exist. Otherwise, you can't write `getattr(my_dict, 'attr_does_not_exit', 100)` (it'll raise `KeyError`, it won't return to you the default value).

**Comment by joealcorn** [comment]
Right you are, thanks
